var fs=require('fs')
var _=require('lodash')

module.exports={    
    OnStartDocument:{
        "Type":"String",
        "Default":"EMPTY"
    },
    OnCreateDocument:{
        "Type":"String",
        "Default":"EMPTY"
    },
    ParentStack:{
        "Type":"String"
    },
    SSMLogGroup:{
        "Type":"String"
    },
    LogsBucket:{
        "Type":"String"
    },
    "EFS":{
        "Type":"String"
    },
    "InstanceType":{
        "Type":"String"
    },
    "RoleArn":{
        "Type":"String"
    },
    "KmsKeyId":{
        "Type":"String",
        "Default":"EMPTY"
    },
    "SecurityGroupId":{
        "Type":"String",
    },
    "SubnetId":{
        "Type":"String",
    },
    "DirectInternetAccess":{
        "Type":"String",
        "Default":"Enabled"
    },
    "IdleShutdown":{
        "Type":"String",
        "Default":"30"
    },
    "GlueDevEndpoint":{
        "Type":"String",
        "Default":"EMPTY"
    }
}

